import { useState, useEffect } from "react";
import TableDetalle from "../Tables/table";
import SidebarLT1 from "../aside/sidebarLT1";
import HeaderLT1 from "../header/headerLT1";

const AdminList = () => {
  const [datos, setDatos] = useState([]);

  useEffect(() => {
    // Se establecen los datos una vez que el componente se monta
    setDatos([
      {
        id: 1,
        nombre: "Juan",
        apellido: "Perez",
        email: "juan.perez@example.com",
        password: "123",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: 2,
        nombre: "María",
        apellido: "González",
        email: "maria.gonzalez@example.com",
        password: "456",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 3,
        nombre: "Pedro",
        apellido: "López",
        email: "pedro.lopez@example.com",
        password: "789",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: 4,
        nombre: "Ana",
        apellido: "Martínez",
        email: "ana.martinez@example.com",
        password: "abc",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 5,
        nombre: "Carlos",
        apellido: "Sánchez",
        email: "carlos.sanchez@example.com",
        password: "def",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 6,
        nombre: "Laura",
        apellido: "Fernández",
        email: "laura.fernandez@example.com",
        password: "ghi",
        rol: "Administrador",
        estado: "Inactivo",
      },
      {
        id: 7,
        nombre: "Daniel",
        apellido: "Gómez",
        email: "daniel.gomez@example.com",
        password: "jkl",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 8,
        nombre: "Sofía",
        apellido: "Díaz",
        email: "sofia.diaz@example.com",
        password: "mno",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 9,
        nombre: "Pablo",
        apellido: "Rodríguez",
        email: "pablo.rodriguez@example.com",
        password: "pqr",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: 10,
        nombre: "Elena",
        apellido: "López",
        email: "elena.lopez@example.com",
        password: "stu",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 11,
        nombre: "Mario",
        apellido: "Hernández",
        email: "mario.hernandez@example.com",
        password: "vwx",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 12,
        nombre: "Luisa",
        apellido: "Martín",
        email: "luisa.martin@example.com",
        password: "yz1",
        rol: "Administrador",
        estado: "Inactivo",
      },
      {
        id: 13,
        nombre: "Javier",
        apellido: "García",
        email: "javier.garcia@example.com",
        password: "234",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 14,
        nombre: "Marcela",
        apellido: "Soto",
        email: "marcela.soto@example.com",
        password: "567",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 15,
        nombre: "Cristian",
        apellido: "Romero",
        email: "cristian.romero@example.com",
        password: "890",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: 16,
        nombre: "Valeria",
        apellido: "Navarro",
        email: "valeria.navarro@example.com",
        password: "abc1",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 17,
        nombre: "Germán",
        apellido: "Ruíz",
        email: "german.ruiz@example.com",
        password: "def2",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 18,
        nombre: "Isabel",
        apellido: "Gutiérrez",
        email: "isabel.gutierrez@example.com",
        password: "ghi3",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: 19,
        nombre: "Diego",
        apellido: "López",
        email: "diego.lopez@example.com",
        password: "jkl4",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 20,
        nombre: "Paula",
        apellido: "Fernández",
        email: "paula.fernandez@example.com",
        password: "mno5",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 21,
        nombre: "Roberto",
        apellido: "Díaz",
        email: "roberto.diaz@example.com",
        password: "pqr6",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: 22,
        nombre: "Sara",
        apellido: "Ruiz",
        email: "sara.ruiz@example.com",
        password: "stu7",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 23,
        nombre: "Martín",
        apellido: "Hernández",
        email: "martin.hernandez@example.com",
        password: "vwx8",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 24,
        nombre: "Lucía",
        apellido: "Gómez",
        email: "lucia.gomez@example.com",
        password: "yz19",
        rol: "Administrador",
        estado: "Inactivo",
      },
      {
        id: 25,
        nombre: "Laura",
        apellido: "García",
        email: "laura.garcia@example.com",
        password: "2340",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 26,
        nombre: "Francisco",
        apellido: "Martínez",
        email: "francisco.martinez@example.com",
        password: "5671",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 27,
        nombre: "Eva",
        apellido: "Martín",
        email: "eva.martin@example.com",
        password: "8902",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: 28,
        nombre: "Jorge",
        apellido: "Hernández",
        email: "jorge.hernandez@example.com",
        password: "abc13",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 29,
        nombre: "Marta",
        apellido: "Gutiérrez",
        email: "marta.gutierrez@example.com",
        password: "def24",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 30,
        nombre: "Alberto",
        apellido: "Sánchez",
        email: "alberto.sanchez@example.com",
        password: "ghi35",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: 31,
        nombre: "Carolina",
        apellido: "Pérez",
        email: "carolina.perez@example.com",
        password: "jkl46",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 1,
        nombre: "Juan",
        apellido: "Perez",
        email: "juan.perez@example.com",
        password: "123",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: 2,
        nombre: "María",
        apellido: "González",
        email: "maria.gonzalez@example.com",
        password: "456",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 3,
        nombre: "Pedro",
        apellido: "López",
        email: "pedro.lopez@example.com",
        password: "789",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: 4,
        nombre: "Ana",
        apellido: "Martínez",
        email: "ana.martinez@example.com",
        password: "abc",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 5,
        nombre: "Carlos",
        apellido: "Sánchez",
        email: "carlos.sanchez@example.com",
        password: "def",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 6,
        nombre: "Laura",
        apellido: "Fernández",
        email: "laura.fernandez@example.com",
        password: "ghi",
        rol: "Administrador",
        estado: "Inactivo",
      },
      {
        id: 7,
        nombre: "Daniel",
        apellido: "Gómez",
        email: "daniel.gomez@example.com",
        password: "jkl",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 8,
        nombre: "Sofía",
        apellido: "Díaz",
        email: "sofia.diaz@example.com",
        password: "mno",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 9,
        nombre: "Pablo",
        apellido: "Rodríguez",
        email: "pablo.rodriguez@example.com",
        password: "pqr",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: 10,
        nombre: "Elena",
        apellido: "López",
        email: "elena.lopez@example.com",
        password: "stu",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 11,
        nombre: "Mario",
        apellido: "Hernández",
        email: "mario.hernandez@example.com",
        password: "vwx",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 12,
        nombre: "Luisa",
        apellido: "Martín",
        email: "luisa.martin@example.com",
        password: "yz1",
        rol: "Administrador",
        estado: "Inactivo",
      },
      {
        id: 13,
        nombre: "Javier",
        apellido: "García",
        email: "javier.garcia@example.com",
        password: "234",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 14,
        nombre: "Marcela",
        apellido: "Soto",
        email: "marcela.soto@example.com",
        password: "567",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 15,
        nombre: "Cristian",
        apellido: "Romero",
        email: "cristian.romero@example.com",
        password: "890",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: 16,
        nombre: "Valeria",
        apellido: "Navarro",
        email: "valeria.navarro@example.com",
        password: "abc1",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 17,
        nombre: "Germán",
        apellido: "Ruíz",
        email: "german.ruiz@example.com",
        password: "def2",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 18,
        nombre: "Isabel",
        apellido: "Gutiérrez",
        email: "isabel.gutierrez@example.com",
        password: "ghi3",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: 19,
        nombre: "Diego",
        apellido: "López",
        email: "diego.lopez@example.com",
        password: "jkl4",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 20,
        nombre: "Paula",
        apellido: "Fernández",
        email: "paula.fernandez@example.com",
        password: "mno5",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 21,
        nombre: "Roberto",
        apellido: "Díaz",
        email: "roberto.diaz@example.com",
        password: "pqr6",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: 22,
        nombre: "Sara",
        apellido: "Ruiz",
        email: "sara.ruiz@example.com",
        password: "stu7",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 23,
        nombre: "Martín",
        apellido: "Hernández",
        email: "martin.hernandez@example.com",
        password: "vwx8",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 24,
        nombre: "Lucía",
        apellido: "Gómez",
        email: "lucia.gomez@example.com",
        password: "yz19",
        rol: "Administrador",
        estado: "Inactivo",
      },
      {
        id: 25,
        nombre: "Laura",
        apellido: "García",
        email: "laura.garcia@example.com",
        password: "2340",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 26,
        nombre: "Francisco",
        apellido: "Martínez",
        email: "francisco.martinez@example.com",
        password: "5671",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 27,
        nombre: "Eva",
        apellido: "Martín",
        email: "eva.martin@example.com",
        password: "8902",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: 28,
        nombre: "Jorge",
        apellido: "Hernández",
        email: "jorge.hernandez@example.com",
        password: "abc13",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 29,
        nombre: "Marta",
        apellido: "Gutiérrez",
        email: "marta.gutierrez@example.com",
        password: "def24",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 30,
        nombre: "Alberto",
        apellido: "Sánchez",
        email: "alberto.sanchez@example.com",
        password: "ghi35",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: 31,
        nombre: "Carolina",
        apellido: "Pérez",
        email: "carolina.perez@example.com",
        password: "jkl46",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 1,
        nombre: "Juan",
        apellido: "Perez",
        email: "juan.perez@example.com",
        password: "123",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: 2,
        nombre: "María",
        apellido: "González",
        email: "maria.gonzalez@example.com",
        password: "456",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 3,
        nombre: "Pedro",
        apellido: "López",
        email: "pedro.lopez@example.com",
        password: "789",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: 4,
        nombre: "Ana",
        apellido: "Martínez",
        email: "ana.martinez@example.com",
        password: "abc",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 5,
        nombre: "Carlos",
        apellido: "Sánchez",
        email: "carlos.sanchez@example.com",
        password: "def",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 6,
        nombre: "Laura",
        apellido: "Fernández",
        email: "laura.fernandez@example.com",
        password: "ghi",
        rol: "Administrador",
        estado: "Inactivo",
      },
      {
        id: 7,
        nombre: "Daniel",
        apellido: "Gómez",
        email: "daniel.gomez@example.com",
        password: "jkl",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 8,
        nombre: "Sofía",
        apellido: "Díaz",
        email: "sofia.diaz@example.com",
        password: "mno",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 9,
        nombre: "Pablo",
        apellido: "Rodríguez",
        email: "pablo.rodriguez@example.com",
        password: "pqr",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: 10,
        nombre: "Elena",
        apellido: "López",
        email: "elena.lopez@example.com",
        password: "stu",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 11,
        nombre: "Mario",
        apellido: "Hernández",
        email: "mario.hernandez@example.com",
        password: "vwx",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 12,
        nombre: "Luisa",
        apellido: "Martín",
        email: "luisa.martin@example.com",
        password: "yz1",
        rol: "Administrador",
        estado: "Inactivo",
      },
      {
        id: 13,
        nombre: "Javier",
        apellido: "García",
        email: "javier.garcia@example.com",
        password: "234",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 14,
        nombre: "Marcela",
        apellido: "Soto",
        email: "marcela.soto@example.com",
        password: "567",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 15,
        nombre: "Cristian",
        apellido: "Romero",
        email: "cristian.romero@example.com",
        password: "890",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: 16,
        nombre: "Valeria",
        apellido: "Navarro",
        email: "valeria.navarro@example.com",
        password: "abc1",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 17,
        nombre: "Germán",
        apellido: "Ruíz",
        email: "german.ruiz@example.com",
        password: "def2",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 18,
        nombre: "Isabel",
        apellido: "Gutiérrez",
        email: "isabel.gutierrez@example.com",
        password: "ghi3",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: 19,
        nombre: "Diego",
        apellido: "López",
        email: "diego.lopez@example.com",
        password: "jkl4",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 20,
        nombre: "Paula",
        apellido: "Fernández",
        email: "paula.fernandez@example.com",
        password: "mno5",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 21,
        nombre: "Roberto",
        apellido: "Díaz",
        email: "roberto.diaz@example.com",
        password: "pqr6",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: 22,
        nombre: "Sara",
        apellido: "Ruiz",
        email: "sara.ruiz@example.com",
        password: "stu7",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 23,
        nombre: "Martín",
        apellido: "Hernández",
        email: "martin.hernandez@example.com",
        password: "vwx8",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 24,
        nombre: "Lucía",
        apellido: "Gómez",
        email: "lucia.gomez@example.com",
        password: "yz19",
        rol: "Administrador",
        estado: "Inactivo",
      },
      {
        id: 25,
        nombre: "Laura",
        apellido: "García",
        email: "laura.garcia@example.com",
        password: "2340",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 26,
        nombre: "Francisco",
        apellido: "Martínez",
        email: "francisco.martinez@example.com",
        password: "5671",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 27,
        nombre: "Eva",
        apellido: "Martín",
        email: "eva.martin@example.com",
        password: "8902",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: 28,
        nombre: "Jorge",
        apellido: "Hernández",
        email: "jorge.hernandez@example.com",
        password: "abc13",
        rol: "Usuario",
        estado: "Activo",
      },
      {
        id: 29,
        nombre: "Marta",
        apellido: "Gutiérrez",
        email: "marta.gutierrez@example.com",
        password: "def24",
        rol: "Usuario",
        estado: "Inactivo",
      },
      {
        id: 30,
        nombre: "Alberto",
        apellido: "Sánchez",
        email: "alberto.sanchez@example.com",
        password: "ghi35",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: 31,
        nombre: "Carolina",
        apellido: "Pérez",
        email: "carolina.perez@example.com",
        password: "jkl46",
        rol: "Usuario",
        estado: "Activo",
      },
    ]);
  }, []); // Se pasa un arreglo vacío como dependencia para que el efecto se ejecute solo una vez

  return (
    <div className="App">
      <div id="body">
        <HeaderLT1 />
        <section
          style={{ alignItems: "stretch", flexWrap: "nowrap", padding: 0 }}
        >
          <SidebarLT1 />
          <div className="container mt-0">
            {datos.length > 0 && (
              <TableDetalle header={[...Object.keys(datos[0])]} data={datos} />
            )}
          </div>
        </section>
      </div>
    </div>
  );
};

export default AdminList;
